### ISSUE TITLE
Question: Can the auth flow to GitHub be initiated without the Cognito Hosted UI?

### ISSUE THREAD

**Issue by bensullivan** [TimothyJones/github-cognito-openid-wrapper#50] opened 2021-03-19 08:44 UTC
Hi

We've got the flow setup which is great - thanks heaps for open sourcing this!!

Only thing is the UX is kinda sucky with the Cognito Hosted UI.  We also already have a custom login flow using React and aws sdk calls.

Given the shim is behind the scenes, can the auth flow to GitHub via the shim be initiated using an sdk call from our React app?

Thanks!

Ben

**Comment by TimothyJones** [comment] 2021-03-19 10:50
(Also, I will post the link tomorrow if I don’t hear back)

**Comment by bensullivan** [comment] 2021-03-20 00:47
Ah ok that's great news.

Your doco is very clear and detailed which is good as these OAuth and OIDC flows I find complex.  Your flow diagrams are really helpful.  

I guess I only assumed you had to use Hosted UI because the second bullet point in section "1: Setup" links to an AWS doco page entitled: "Add an App to Enable the Hosted Web UI".  I've checked the AWS SDK doco and I can't see anything obvious that initiates the flow to GitHub directly without supplying creds to Cognito...

Thanks again for your help.

Ben

**Comment by TimothyJones** [comment] 2021-03-20 05:20
Oh, thanks! I'm really glad it's helpful.

I think what you're looking for is the `identity_provider` parameter for the `AUTHORIZATION` endpoint. https://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html 

If you supply that parameter directly (I believe the right value is the name of your app that you configured in Cognito - so `GitHubShim` in the documentation screenshots), then you won't see the hosted UI, and will be redirected to the shim (which will redirect to github).

I think you can also disable the hosted UI if you need to do that (although if you set it so that the github shim is the only "app" allowed through the hosted UI, then the whole hosted UI will just be a single button).

**Comment by bensullivan** [comment] 2021-03-21 00:01
Yeah ok so AWS confirmed the same - the endpoint should look like:

https://<your Cognito domain>/oauth2/authorize?identity_provider=<OIDC Provider name>&redirect_uri=<callback URL>&response_type=TOKEN&client_id=<app client id>&scope=email  openid profile

**Comment by TimothyJones** [comment] 2021-03-21 04:05
> Does this call need all three scopes for the shim to function correctly?

I don't think so. Those scopes aren't pushed to the shim. I think you only need `openid`, plus any custom scopes you require from your cognito user pool.

> Apparently, one can also use the SDK

Yes, this is possible. I don't personally see why anyone would use the SDK, though - since Cognito provides an OpenID connect-compatible interface, you can use that and not tie yourself to cognito. The SDK probably has some advantage that I have never needed- it might help if you're using Identity Pools, maybe.

**Comment by TimothyJones** [comment] 2021-03-21 04:08
Looks like the link there is about direct access to the IDP (without involving the user pool), which might be exactly what you want if you're not using cognito's user. Although, if that's what you want, then I would do direct access to the shim instead?

**Comment by bensullivan** [comment] 2021-03-21 06:21
Well my understanding was that the shim (or is it Cognito?) create a user in Cognito when an authorisation is granted with a 3rd party OIDC provider?

> Looks like the link there

Which link are you referring to?  `authorize` endpoint or the amplify AWS doc link?

I think we’ll keep the users in Cognito and just use the 3rd party providers for authn/z..

**Comment by bensullivan** [comment] 2021-03-21 06:26
How do you normally logout a user when you have the shim in play?  I'm thinking of the scenario where one has authorized cognito in github and then user logs out of github.  How does one force the cognito session to expire as well?

And conversely, if one logs out of cognito, does the shim remove the authorised clients in the GitHib OAuth app?

**Comment by TimothyJones** [comment] 2021-03-21 08:26
> How do you normally logout a user when you have the shim in play?

Just log them out of Cognito the same way you would without the shim. This is because users are logging in with Cognito, not the shim. 

Your client app doesn't know about github, it only knows about Cognito. It is up to Cognito how to handle authentication. Now, Cognito is optionally (and in your case, entirely, I think) delegating its authentication to github. So, Cognito knows about github (well, it knows about the shim, which knows about github).

This means that if the user logs out of github, they are not logged out of your app. This is the expected behaviour from the user's perspective, because their session with github is not the same as their session with your app.

> And conversely, if one logs out of cognito, does the shim remove the authorised clients in the GitHib OAuth app?

No. This is because the authorised clients are separate to login sessions. The authorisation for your app lives from the moment it is created, until it is cancelled explicitly by the user (from the Applications setting in their profile).

Authentication: Which github user is this (if any)?
Authorisation: Does this github user permit your app to access their github profile?

The login process always does both checks, but after the user has authorised your app the first time, the answer is "yes" until they revoke it.

Last I checked, github sessions never expire. If this is still the case, then the behaviour for a user who has previously logged in to your app (and authorised it in github) is: 

1) If they are logged out of both github and your app, they see the github login page
2) If they are logged in to github, but out of your app, they are immediately redirected to a successful login session in your app.

If you have a challenging scenario or use case, I'd be happy to do a couple of days consulting with you help get to the bottom of it - my email is in my profile.

**Comment by TimothyJones** [comment] 2021-03-21 08:42
> Which link are you referring to? authorize endpoint or the amplify AWS doc link?

Sorry, I wasn't clear. I meant that AWS Amplify link. I'm not super familiar with Amplify, though- take my read with a grain of salt. I also realise now that your original question asked about the aws sdk - apologies, I missed this on the first read.

Personally, unless there's a compelling reason to use the Amplify SDK for logins, I'd just use the [Auth API endpoints](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-userpools-server-contract-reference.html), which follow the OpenID Connect spec. This has the very nice advantage that it will be very simple if you ever migrate your auth away from Cognito.

If you want a library for it, there are a number of React OpenID Connect implementations - [this one looks straightforward](https://github.com/skoruba/react-oidc-client-js), although the react is a bit old school. It's also very simple to implement your own if you prefer a different interface.

In a React app, you definitely want to use the Authorisation Code flow with PKCE - [this article](https://auth0.com/docs/flows/authorization-code-flow-with-proof-key-for-code-exchange-pkce) is an excellent summary about why (in fact, the Auth0 documentation in general is very good for explaining how OpenID Connect works).

**Comment by TimothyJones** [comment] 2021-03-21 08:50
> Well my understanding was that the shim (or is it Cognito?) create a user in Cognito when an authorisation is granted with a 3rd party OIDC provider?

This is pretty much right, although Cognito creates the user. When a user logs in, Cognito uses the `userinfo` endpoint on the shim to find out what information it should create (or update) in its user pool. The shim doesn't know about Cognito (except for the redirect URI).

> I think we’ll keep the users in Cognito and just use the 3rd party providers for authn/z..

I think this is a good design, and from what you've described so far, it's also what I would do.

**Comment by TimothyJones** [comment] 2021-03-21 08:54
I'll close this for now, feel free to reopen or contact me by email if you need further clarification. As implied above, I've also got some limited availability at the moment, if you'd like me to take a more detailed look at your scenario.

**Closed by TimothyJones** 2021-03-21 08:54 UTC

**Comment by bensullivan** [comment] 2021-03-22 02:20
Hello again Timothy,

Apologies just one more question (couldn't see how to reopen the issue) - from your flow diagrams, it seems that one would be able to use the access token provided by Cognito (that the shim has retrieved behind the scenes) to access GitHub directly?  That is, the access token provided to the shim from github is passed back to the Cognito client - is that right?  

Reason I ask is that we might need to directly trigger (ie for headless integration with no front end) functionality in our API that has dependencies on GitHub APIs and in that case we'd only have an API key as a means of identifying the request sender unless we piggy backed the github access token into the request as well...

**Comment by bensullivan** [comment] 2021-03-22 02:24
Hmm ignore me - I think I've just realised I'm talking about a GitHub personal access token :-)

**Comment by TimothyJones** [comment] 2021-03-22 04:23
No, that’s not correct. You get a cognito access token from cognito. Again, your app doesn’t know about GitHub, it only knows about cognito.

Cognito uses the GitHub access token to federate with GitHub and get the user’s details. It doesn’t pass that token on to its clients.
